#version 460 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D texture0;

uniform bool mousePressed;
uniform ivec2 mousePos;
uniform ivec2 winSize;

const vec4 SAND_COLOR = vec4(1.0, 1.0, 0.0, 1.0);
const vec4 CLEAR_COLOR = vec4(0);

ivec2 brushSize = ivec2(80, 80);

bool isBetween(int number, int x0, int x1) {
    return number > x0 && number < x1;
}

bool isInside(ivec2 point, ivec2 x0, ivec2 x1) {
    return isBetween(point.x, x0.x, x1.x) && isBetween(point.y, x0.y, x1.y);
}

void main() {
    vec4 value = vec4(0);
    ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 texCoordOther = texCoord + ivec2(winSize.x, 0);
    vec4 colorOther = imageLoad(texture0, texCoordOther);

    // copy old image
    imageStore(texture0, texCoord, colorOther);
    vec4 currentColor = imageLoad(texture0, texCoord);


    // clear the render image
    imageStore(texture0, texCoordOther, CLEAR_COLOR);


    // painting
    if (mousePressed) {
        if (isInside(texCoord, mousePos, mousePos + brushSize)) {
            imageStore(texture0, texCoordOther, SAND_COLOR);
        }
    }

    // logic
    bool isDown = texCoord.y == 0;
    if (currentColor == SAND_COLOR) {
        if (!isDown) {
            imageStore(texture0, texCoordOther + ivec2(1, 0), SAND_COLOR);
        }
    }


}
